######################################################################
# Automatically generated by qmake (2.01a) jeu. août 28 20:08:27 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Particle.h Universe.h
SOURCES += main.cpp Particle.cpp Universe.cpp
TRANSLATIONS += newton_fr.ts newton_en.ts
